[package]
name = "registration_form_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
diesel = { version = "2.0.4", features = ["postgres"] }
dotenvy = "0.15.7"
tokio = { version = "1.28.1", features = ["full"] }
