version: '3.8'
services:
  rust-app:
    build:
      context: .
      dockerfile: Docker/rust.dockerfile
    ports:
      - 80:80
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    build:
      context: .
      dockerfile: Docker/postgres.dockerfile
    restart: always
    ports:
      - 5432:5432
